cameras:
  cam_1:
    video_source: "rtsp://admin:EMPJAD@117.5.133.169:554/h264/ch1/main/av_stream"
    src_pts: [[346, 101], [117, 181], [270, 419], [630, 166], [350, 103]]
    real_width: 4.5
    real_length: 18.0
    speed_limit: 25.0
    save_output: false
    output_path: "output_cam_1.mp4"

  # cam_2:
  #   video_source: 1 # Webcam thứ hai (hoặc RTSP URL)
  #   src_pts: [[100, 100], [540, 100], [600, 500], [40, 500]]
  #   real_width: 3.5
  #   real_length: 15.0
  #   speed_limit: 50.0
  #   save_output: false
  #   output_path: "output_cam_2.mp4"
#highway
# line1= [(250, 79), (445, 82)]
# line2= [(94, 342), (597, 354)]
#vidtest
# line1= [(6, 242), (476, 280)]
# line2= [(516, 407), (2, 373)]
#test
# line1= [(307, 342), (622, 342)]
# line2= [(400, 226), (185, 226)]
#OQ
# [191, 122], [69, 161], [295, 531], [624, 317]
# KQ
# [281, 146], [179, 180], [295, 429], [556, 304]